import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f4f5f7' },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: '#d8dee8',
    gap: 0,
    overflow: 'hidden',
  },
  summaryHeaderBar: {
    backgroundColor: '#0f172a',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 4,
  },
  summaryHeaderBarPlain: {
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#d8dee8',
  },
  summaryHeading: { fontSize: 17, fontWeight: '700', color: '#f8fafc' },
  summaryHeadingPlain: { color: '#0f172a' },
  summaryHeaderDate: { fontSize: 12, color: '#cbd5e1' },
  summaryHeaderDatePlain: { color: '#64748b' },
  summaryContent: { gap: 0 },
  summarySubheading: { fontSize: 15, fontWeight: '700', color: '#0f172a', marginTop: 6 },
  summaryText: { fontSize: 14, color: '#334155', lineHeight: 20 },
  opsSection: { gap: 0, marginTop: 0 },
  opsSectionBar: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  opsSectionBarText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  opsSectionBarSwap: {
    backgroundColor: 'rgba(72, 141, 61, 0.67)',
  },
  opsSectionBarMarketplace: {
    backgroundColor: 'rgba(255, 102, 101, 0.9)',
  },
  opsSectionContent: {
    borderWidth: 0,
    borderColor: '#dbe2ea',
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: 'rgba(72, 141, 61, 0.12)',
    padding: 0,
  },
  opsSectionContentMarketplace: {
    borderWidth: 0,
    borderColor: '#dbe2ea',
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: 'rgba(255, 102, 101, 0.12)',
    padding: 0,
  },
  marketplaceTransactionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 102, 101, 0.24)',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopColor: '#000',
    borderTopWidth: 1,
    borderBottomWidth: 1
  },
  marketplaceTransactionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#8f2323',
    textTransform: 'uppercase',
  },
  marketplaceTransactionValue: {
    fontSize: 14,
    fontWeight: '800',
    color: '#7a1d1d',
    flex: 1,
    paddingLeft: 12
  },
  splitAmountSummary: { gap: 0 },
  splitAmountMainCard: {
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: 'rgba(72, 141, 61, 0.24)',
    padding: 16,
  },
  splitAmountMainCardMarketplace: {
    backgroundColor: 'rgba(255, 102, 101, 0.24)',
  },
  splitAmountMainLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#255322',
  },
  splitAmountMainLabelMarketplace: {
    color: '#8f2323',
  },
  splitAmountMainValue: { fontSize: 30, fontWeight: '800', color: '#1d3b19' },
  splitAmountMainValueMarketplace: { color: '#7a1d1d' },
  splitAmountRow: { flexDirection: 'row' },
  splitAmountCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.28)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    padding: 14,
    gap: 4,
  },
  splitAmountCardMarketplace: {
    borderColor: 'rgba(255, 102, 101, 0.28)',
  },
  splitAmountCardLeft: {  },
  splitAmountCardRight: {  },
  splitAmountLabel: { fontSize: 12, color: '#255322', fontWeight: '600' },
  splitAmountLabelMarketplace: { color: '#8f2323' },
  splitAmountValue: { fontSize: 20, color: '#1d3b19', fontWeight: '800' },
  splitAmountValueMarketplace: { color: '#7a1d1d' },
  titleCategorizedSummary: {
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.28)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderTopColor: '#000',
  },
  titleCategorizedSummaryMarketplace: {
    borderColor: 'rgba(255, 102, 101, 0.28)',
  },
  titleCategorizedSummaryHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  titleCategorizedSummaryTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1d3b19',
    textTransform: 'uppercase',
  },
  titleCategorizedSummaryTitleMarketplace: { color: '#7a1d1d' },
  titleCategorizedSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    gap: 0
  },
  titleCategorizedSummaryCard: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: '30%',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderWidth: 0.5,
    borderColor: 'rgba(72, 141, 61, 0.2)',
    padding: 14,
    gap: 8,
  },
  titleCategorizedSummaryCardMarketplace: {
    borderColor: 'rgba(255, 102, 101, 0.2)',
  },
  titleCategorizedSummaryLabel: { fontSize: 12, lineHeight: 16, color: '#255322', fontWeight: '600' },
  titleCategorizedSummaryLabelMarketplace: { color: '#8f2323' },
  titleCategorizedSummaryValue: { fontSize: 22, color: '#1d3b19', fontWeight: '800' },
  titleCategorizedSummaryValueMarketplace: { color: '#7a1d1d' },
  opsGridScroll: { paddingRight: 4 },
  opsGridContent: {
    minWidth: 552,
    backgroundColor: '#eef2f7',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    borderTopWidth: 0,
    padding: 10,
    gap: 10,
  },
  opsMetricRow: { flexDirection: 'row', gap: 10 },
  opsMetricCard: {
    width: 123,
    minHeight: 110,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    justifyContent: 'space-between',
  },
  opsMetricCardSwap: { backgroundColor: '#ffe8e6', borderColor: '#fecaca' },
  opsMetricCardMarketplace: { backgroundColor: '#e7f7ef', borderColor: '#bbf7d0' },
  opsMetricValue: { fontSize: 28, fontWeight: '800', color: '#0f172a' },
  opsMetricLabel: { fontSize: 12, lineHeight: 16, color: '#475569' },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#ececf1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: { paddingVertical: 8, paddingHorizontal: 10, backgroundColor: '#f1f2f5', borderRadius: 10 },
  backText: { color: '#222', fontWeight: '600' },
  backPlaceholder: { width: 72 },
  headerTitle: { fontSize: 20, fontWeight: '700', color: '#0f172a' },
  headerSubtitle: { fontSize: 12, color: '#64748b', marginTop: 2 },
  content: { padding: 16, gap: 12 },
  tabsRow: { flexDirection: 'row', gap: 10 },
  tabsBar: {
    marginHorizontal: -16,
    marginTop: -16,
    backgroundColor: '#0f172a',
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    gap: 10,
  },
  tabsBarAlt: {
    marginHorizontal: -16,
    marginTop: -16,
    backgroundColor: '#1e293b',
    paddingVertical: 8,
  },
  tabsBarScrollContent: {
    paddingHorizontal: 16,
    gap: 10,
  },
  tabsBarButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  tabsBarButtonActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  tabsBarButtonText: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '700',
  },
  tabsBarButtonTextActive: {
    color: '#ffffff',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#fff',
  },
  tabButtonActive: { backgroundColor: '#0f172a', borderColor: '#0f172a' },
  tabButtonText: { fontSize: 14, fontWeight: '700', color: '#0f172a', textAlign: 'center' },
  tabButtonTextActive: { color: '#fff' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  profileHeader: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    gap: 4,
  },
  profileName: { fontSize: 22, fontWeight: '700', color: '#0f172a' },
  profileEmail: { fontSize: 14, color: '#475569' },
  card: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb', padding: 14, gap: 6 },
  cardActive: { borderColor: '#0f766e', backgroundColor: '#f0fdfa' },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#111827' },
  cardSubtitle: { fontSize: 13, color: '#4b5563', lineHeight: 18 },
  helperText: { fontSize: 12, color: '#64748b', lineHeight: 18 },
  listItem: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb', padding: 14, gap: 6, marginBottom: 10 },
  pressableListItem: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 6,
    marginBottom: 10,
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  rowLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase' },
  rowValue: { color: '#111827', fontSize: 13, fontWeight: '600' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  statCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 6,
  },
  statLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase' },
  statValue: { color: '#111827', fontSize: 16, fontWeight: '700' },
  overviewTable: {
    backgroundColor: 'rgba(72, 141, 61, 0.12)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.22)',
    overflow: 'hidden',
  },
  overviewTableRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.66)',
  },
  overviewTableRowBorder: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(72, 141, 61, 0.18)',
  },
  overviewTableCell: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 6,
  },
  overviewTableCellWithDivider: {
    borderRightWidth: 1,
    borderRightColor: 'rgba(72, 141, 61, 0.18)',
  },
  overviewTableLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#255322',
  },
  overviewTableValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1d3b19',
  },
  overviewTableLinkValue: {
    textDecorationLine: 'underline',
  },
  overviewTableHint: {
    fontSize: 12,
    lineHeight: 16,
    color: '#476543',
  },
  overviewActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  overviewActionButton: {
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 150,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.22)',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 6,
  },
  overviewActionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1d3b19',
  },
  overviewActionSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#476543',
  },
  overviewDivider: {
    height: 1,
    backgroundColor: 'rgba(37, 83, 34, 0.2)',
    marginVertical: 2,
  },
  overviewMoreActionsPanel: {
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.22)',
    overflow: 'hidden',
  },
  overviewMoreActionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  overviewMoreActionsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1d3b19',
  },
  overviewMoreActionsToggle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#476543',
    textTransform: 'uppercase',
  },
  overviewMoreActionsBody: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    gap: 10,
  },
  overviewSecondaryActionButton: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.2)',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  overviewSecondaryActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1d3b19',
  },
  selectLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase', marginBottom: 6 },
  actionRow: { marginTop: 10, flexDirection: 'row', gap: 8 },
  approveBtn: { flex: 1, backgroundColor: '#059669', borderRadius: 10, padding: 10, alignItems: 'center' },
  rejectBtn: { flex: 1, backgroundColor: '#dc2626', borderRadius: 10, padding: 10, alignItems: 'center' },
  btnText: { color: '#fff', fontWeight: '700' },
  primaryButton: {
    backgroundColor: '#0f172a',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  primaryButtonDisabled: { backgroundColor: '#cbd5e1' },
  primaryButtonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#94a3b8',
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  secondaryButtonText: { color: '#0f172a', fontWeight: '700' },
  input: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#d1d5db', paddingHorizontal: 14, paddingVertical: 12, color: '#111827' },
  inputWithSpacing: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#111827',
    marginTop: 8,
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 10,
  },
  itemRow: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 12,
    marginBottom: 10,
    flexDirection: 'row',
  },
  itemImage: { width: 76, height: 76, borderRadius: 12, backgroundColor: '#e5e7eb' },
  itemDetails: { flex: 1, gap: 6 },
  itemMeta: { fontSize: 13, color: '#475569' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
  },
  chipActive: { borderColor: '#0f766e', backgroundColor: '#f0fdfa' },
  chipText: { fontSize: 13, fontWeight: '600', color: '#334155' },
  scannerCard: {
    backgroundColor: '#ecfeff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#a5f3fc',
    padding: 14,
    gap: 6,
  },
  cameraFrame: {
    marginTop: 8,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#67e8f9',
    backgroundColor: '#0f172a',
  },
  cameraPreview: {
    width: '100%',
    height: 280,
  },
  quickActionsRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  quickActionButton: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingVertical: 12,
    alignItems: 'center',
  },
  quickActionButtonActive: { backgroundColor: '#ecfeff', borderColor: '#0e7490' },
  quickActionText: { color: '#0f172a', fontWeight: '700', fontSize: 12 },
  reportHeaderCard: {
    backgroundColor: '#0f172a',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#111827',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportHeaderTitle: { color: '#f8fafc', fontWeight: '700', fontSize: 16 },
  reportBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#86efac',
    backgroundColor: '#14532d',
  },
  reportBadgeText: { color: '#dcfce7', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
  datePickerRow: { flexDirection: 'row', gap: 10 },
  datePickerButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  datePickerLabel: { color: '#64748b', fontSize: 11, textTransform: 'uppercase', fontWeight: '600' },
  datePickerValue: { color: '#0f172a', fontSize: 14, fontWeight: '700' },
  reportCardsGrid: { gap: 10 },
  loginPage: {
    flex: 1,
  },
  loginSafeArea: {
    flex: 1,
  },
  loginScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
    justifyContent: 'center',
  },
  loginContainer: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  loginBranding: {
    alignItems: 'center',
    marginBottom: 40,
  },
  loginAppName: {
    fontSize: 36,
    fontWeight: '700',
    marginBottom: 24,
    color: '#ffffff',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  loginLogoContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  loginLogo: {
    width: 120,
    height: 120,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: '#ffffff',
  },
  loginVersion: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '500',
  },
  loginCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  loginCardHeader: {
    paddingHorizontal: 32,
    paddingTop: 32,
    paddingBottom: 24,
    backgroundColor: '#f4f2ff',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  loginCardTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 8,
    textAlign: 'center',
  },
  loginCardSubtitle: {
    fontSize: 15,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  loginCardContent: {
    padding: 32,
  },
  loginFormGroup: {
    marginBottom: 24,
  },
  loginFormLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 8,
  },
  loginFormInput: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#2c3e50',
    backgroundColor: '#f8f9fa',
    borderWidth: 2,
    borderColor: '#e9ecef',
    borderRadius: 10,
  },
  loginErrorMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#ffeeee',
    borderWidth: 1,
    borderColor: '#ffcccc',
    borderRadius: 8,
    marginBottom: 24,
  },
  loginErrorIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    textAlign: 'center',
    textAlignVertical: 'center',
    overflow: 'hidden',
    color: '#c33',
    fontWeight: '800',
  },
  loginErrorText: {
    flex: 1,
    color: '#c33',
    fontSize: 14,
  },
  loginButton: {
    width: '100%',
    minHeight: 52,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6b63ea',
  },
  loginButtonDisabled: {
    opacity: 0.7,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  splashScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  splashContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  splashLogo: {
    width: 124,
    height: 124,
    marginBottom: 20,
  },
  splashAppName: {
    fontSize: 30,
    fontWeight: '700',
    color: '#0f172a',
    textAlign: 'center',
  },
  splashVersion: {
    marginTop: 8,
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
  },
  splashLoadingText: {
    marginTop: 28,
    fontSize: 16,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
  },
  checkoutSummaryCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(72, 141, 61, 0.22)',
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  checkoutSummaryHeader: {
    backgroundColor: 'rgba(72, 141, 61, 0.67)',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  checkoutSummaryHeaderText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  checkoutSummaryBody: {
    backgroundColor: 'rgba(72, 141, 61, 0.12)',
    padding: 12,
    gap: 10,
  },
  checkoutList: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  checkoutListItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  checkoutListItemLast: {
    borderBottomWidth: 0,
  },
});
