import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f4f5f7' },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d8dee8',
    padding: 16,
    gap: 0,
  },
  summaryHeading: { fontSize: 17, fontWeight: '700', color: '#0f172a' },
  summarySubheading: { fontSize: 15, fontWeight: '700', color: '#0f172a', marginTop: 6 },
  summaryText: { fontSize: 14, color: '#334155', lineHeight: 20 },
  opsSection: { gap: 0, marginTop: 10 },
  opsSectionBar: {
    backgroundColor: '#0f172a',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  opsSectionBarText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  opsGridScroll: { paddingRight: 4 },
  opsGridContent: {
    minWidth: 552,
    backgroundColor: '#eef2f7',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    borderTopWidth: 0,
    padding: 10,
    gap: 10,
  },
  opsMetricRow: { flexDirection: 'row', gap: 10 },
  opsMetricCard: {
    width: 123,
    minHeight: 110,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    justifyContent: 'space-between',
  },
  opsMetricCardSwap: { backgroundColor: '#ffe8e6', borderColor: '#fecaca' },
  opsMetricCardMarketplace: { backgroundColor: '#e7f7ef', borderColor: '#bbf7d0' },
  opsMetricValue: { fontSize: 28, fontWeight: '800', color: '#0f172a' },
  opsMetricLabel: { fontSize: 12, lineHeight: 16, color: '#475569' },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#ececf1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: { paddingVertical: 8, paddingHorizontal: 10, backgroundColor: '#f1f2f5', borderRadius: 10 },
  backText: { color: '#222', fontWeight: '600' },
  backPlaceholder: { width: 72 },
  headerTitle: { fontSize: 20, fontWeight: '700', color: '#0f172a' },
  headerSubtitle: { fontSize: 12, color: '#64748b', marginTop: 2 },
  content: { padding: 16, gap: 12 },
  tabsRow: { flexDirection: 'row', gap: 10 },
  tabButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#dbe2ea',
    backgroundColor: '#fff',
  },
  tabButtonActive: { backgroundColor: '#0f172a', borderColor: '#0f172a' },
  tabButtonText: { fontSize: 14, fontWeight: '700', color: '#0f172a', textAlign: 'center' },
  tabButtonTextActive: { color: '#fff' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  profileHeader: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    gap: 4,
  },
  profileName: { fontSize: 22, fontWeight: '700', color: '#0f172a' },
  profileEmail: { fontSize: 14, color: '#475569' },
  card: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb', padding: 14, gap: 6 },
  cardActive: { borderColor: '#0f766e', backgroundColor: '#f0fdfa' },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#111827' },
  cardSubtitle: { fontSize: 13, color: '#4b5563', lineHeight: 18 },
  helperText: { fontSize: 12, color: '#64748b', lineHeight: 18 },
  listItem: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb', padding: 14, gap: 6, marginBottom: 10 },
  pressableListItem: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 6,
    marginBottom: 10,
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  rowLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase' },
  rowValue: { color: '#111827', fontSize: 13, fontWeight: '600' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  statCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 6,
  },
  statLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase' },
  statValue: { color: '#111827', fontSize: 16, fontWeight: '700' },
  selectLabel: { color: '#6b7280', fontSize: 12, textTransform: 'uppercase', marginBottom: 6 },
  actionRow: { marginTop: 10, flexDirection: 'row', gap: 8 },
  approveBtn: { flex: 1, backgroundColor: '#059669', borderRadius: 10, padding: 10, alignItems: 'center' },
  rejectBtn: { flex: 1, backgroundColor: '#dc2626', borderRadius: 10, padding: 10, alignItems: 'center' },
  btnText: { color: '#fff', fontWeight: '700' },
  primaryButton: {
    backgroundColor: '#0f172a',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryButtonDisabled: { backgroundColor: '#cbd5e1' },
  primaryButtonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#94a3b8',
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryButtonText: { color: '#0f172a', fontWeight: '700' },
  input: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#d1d5db', paddingHorizontal: 14, paddingVertical: 12, color: '#111827' },
  inputWithSpacing: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#111827',
    marginTop: 8,
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 10,
  },
  itemRow: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    gap: 12,
    marginBottom: 10,
    flexDirection: 'row',
  },
  itemImage: { width: 76, height: 76, borderRadius: 12, backgroundColor: '#e5e7eb' },
  itemDetails: { flex: 1, gap: 6 },
  itemMeta: { fontSize: 13, color: '#475569' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
  },
  chipActive: { borderColor: '#0f766e', backgroundColor: '#f0fdfa' },
  chipText: { fontSize: 13, fontWeight: '600', color: '#334155' },
  scannerCard: {
    backgroundColor: '#ecfeff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#a5f3fc',
    padding: 14,
    gap: 6,
  },
  quickActionsRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  quickActionButton: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingVertical: 12,
    alignItems: 'center',
  },
  quickActionText: { color: '#0f172a', fontWeight: '700', fontSize: 12 },
});
